### ISSUE TITLE
Gauntlt docker issue

### ISSUE THREAD

**Issue by vineetapte** [gauntlt/gauntlt-docker#7]
I am getting below error when i run "make build" on gauntlt-docker
Step 6/20 : RUN gem install gauntlt --no-rdoc --no-ri
 ---> Running in 50e1cf3d08a1
Successfully installed builder-3.2.3
Successfully installed diff-lcs-1.3
Successfully installed multi_json-1.13.1
Building native extensions.  This could take a while...
Successfully installed gherkin-2.12.2
Successfully installed multi_test-0.1.2
Successfully installed cucumber-1.3.20
Building native extensions.  This could take a while...
ERROR:  Error installing gauntlt:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/childprocess-1.0.1/ext
/usr/bin/ruby2.3 mkrf_conf.rb

current directory: /var/lib/gems/2.3.0/gems/childprocess-1.0.1/ext
/usr/bin/ruby2.3 -rubygems /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake RUBYARCHDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/childprocess-1.0.1 RUBYLIBDIR=/var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/childprocess-1.0.1
/usr/bin/ruby2.3: No such file or directory -- /usr/share/rubygems-integration/all/gems/rake-10.5.0/bin/rake (LoadError)

rake failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/childprocess-1.0.1 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/childprocess-1.0.1/gem_make.out
The command '/bin/sh -c gem install gauntlt --no-rdoc --no-ri' returned a non-zero code: 1
Makefile:4: recipe for target 'build' failed
make: *** [build] Error 1

Please check. Let me know if you need more info.

**Comment by vineetapte** [comment]
Add below command to the Dockerfile.
RUN gem install rake.

This solved the issue for me.

**Comment by AlekKras** [comment]
It didn't solve the issue for me, @vineetapte .  I have a very same problem and tried what you suggested. Still had the same output. Weird...

**Comment by hemtri1984** [comment]
rake is successfully installed in my system, but still facing the same error:

 ---> 316249cf98df
Step 14/29 : RUN gem install rake
 ---> Running in 7afcb0d0ecc1
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
Successfully installed rake-13.0.3
Parsing documentation for rake-13.0.3
Done installing documentation for rake after 0 seconds
1 gem installed
Removing intermediate container 7afcb0d0ecc1
 ---> f19bbed725f2
Step 15/29 : RUN gem install gauntlt --no-rdoc --no-ri
 ---> Running in 9f7a6e61406e
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --no-rdoc
Did you mean?  no-force
The command '/bin/sh -c gem install gauntlt --no-rdoc --no-ri' returned a non-zero code: 1


Seems like some specific version of rake needs to install.
